{
	"what is alphashore?":"Alphashore is a network in network made easier and less messier.",
	"help":"Ask any help on alphashore in our discord server: https://discord.gg/psYgCGt6Uu",
	"who made alphashore?":"adthoughtsglobal made alphashore",
   "What is the smallest particle in the universe?":"The smallest particle in the universe is currently believed to be quarks, which are elementary particles and a fundamental constituent of matter.",
   "What is the capital of India?":"The capital of India is New Delhi.",
   "nanotechnology":"Nanotechnology is the manipulation and study of matter at the nanoscale, typically in the range of 1 to 100 nanometers.",
   "What is the boiling point of water?":"The boiling point of water at sea level is 100 degrees Celsius (212 degrees Fahrenheit).",
   "What is the currency of Japan?":"The currency of Japan is the Japanese yen (¥).",
   "renewable energy":"Renewable energy is energy that comes from naturally replenished sources, such as sunlight, wind, and water, and is considered environmentally friendly.",
   "What is the chemical symbol for water?":"The chemical symbol for water is H2O.",
   "What is the largest ocean on Earth?":"The largest ocean on Earth is the Pacific Ocean.",
   "What is the capital of Brazil?":"The capital of Brazil is Brasília.",
   "quantum computing":"Quantum computing is a branch of computing that uses quantum-mechanical phenomena, such as superposition and entanglement, to perform operations.",
   "What is the formula for the area of a circle?":"The formula for the area of a circle is A = πr^2, where A is the area and r is the radius of the circle.",
   "What is the meaning of the word technology?":"Technology refers to the application of scientific knowledge for practical purposes, especially in industry and commerce.",
   "global warming":"Global warming is the long-term increase in Earths average surface temperature due to human activities, primarily the release of greenhouse gases.",
   "What is the tallest building in the world?":"As per our sources, the tallest building in the world is the Burj Khalifa in Dubai, United Arab Emirates.",
   "What is the capital of China?":"The capital of China is Beijing.",
   "cybersecurity":"Cybersecurity refers to the protection of computer systems and networks from theft, damage, or unauthorized access to data.",
   "What is the boiling point of nitrogen?":"The boiling point of nitrogen is approximately -195.79 degrees Celsius (-320.42 degrees Fahrenheit).",
   "What is the chemical symbol for oxygen?":"The chemical symbol for oxygen is O.",
   "What is the population of the United States?":"As per our sources, the population of the United States is over 331 million people.",
   "What is the meaning of the word artificial?":"The word artificial refers to something that is made or produced by human beings, often to imitate or replace something natural.",
   "robotics":"Robotics is the interdisciplinary field that involves the design, construction, operation, and application of robots.",
   "What is the capital of Russia?":"The capital of Russia is Moscow.",
   "What is the freezing point of water?":"The freezing point of water at sea level is 0 degrees Celsius (32 degrees Fahrenheit).",
   "What is the currency of the United Kingdom?":"The currency of the United Kingdom is the British pound sterling (£).",
   "the internet of things (IoT)":"The Internet of Things (IoT) refers to the network of physical devices, vehicles, appliances, and other objects embedded with sensors and software that enables them to connect and exchange data over the internet.",
   "What is the chemical symbol for carbon?":"The chemical symbol for carbon is C.",
   "What is the meaning of the word machine?":"The word machine refers to a device that uses mechanical power to perform tasks.",
   "climate change":"Climate change refers to long-term changes in Earths climate, including shifts in temperature, precipitation, and weather patterns, often attributed to human activities.",
   "What is the tallest animal in the world?":"The tallest animal in the world is the giraffe.",
   "What is the capital of Germany?":"The capital of Germany is Berlin.",
   "What is the formula for calculating speed?":"The formula for calculating speed is speed = distance ÷ time.",
   "artificial neural networks":"Artificial neural networks are a type of machine learning model inspired by the structure and function of biological neural networks.",
   "What is the capital of Australia?":"The capital of Australia is Canberra.",
   "Turn on dark mode":"<a onclick=dmode() href=#;D>Click Here</a> to turn on Dark Mode.",
   "machine learning algorithms":"Machine learning algorithms are methods used to train machine learning models to make predictions or decisions based on data.",
   "What is the meaning of the word algorithm?":"The word algorithm refers to a step-by-step procedure or a set of rules for solving a specific problem or performing a specific task.",
   "What is the highest mountain in North America?":"The highest mountain in North America is Denali, also known as Mount McKinley.",
   "What is the capital of South Africa?":"The capital of South Africa is Pretoria.",
   "the concept of big data":"Big data refers to extremely large and complex datasets that require advanced tools and techniques for processing, analyzing, and extracting valuable insights.",
   "What is the chemical symbol for gold?":"The chemical symbol for gold is Au.",
   "What is the meaning of the word data?":"Data refers to facts, statistics, or information that can be collected, analyzed, and used for various purposes.",
   "virtual assistants":"Virtual assistants are AI-powered applications designed to provide users with information and perform tasks through natural language interaction.",
   "What is the currency of Germany?":"The currency of Germany is the Euro (€).",
   "What is the boiling point of mercury?":"The boiling point of mercury is approximately 356.6 degrees Celsius (674.8 degrees Fahrenheit).",
   "What is the chemical symbol for iron?":"The chemical symbol for iron is Fe.",
   "What is the population of China?":"As per our sources, the population of China is over 1.4 billion people, making it the most populous country in the world.",
   "renewable energy sources":"Renewable energy sources include solar, wind, hydro, geothermal, and biomass energy, which are considered sustainable and do not deplete over time.",
   "What is the chemical symbol for hydrogen?":"The chemical symbol for hydrogen is H.",
   "What is the largest desert in the world?":"The largest desert in the world is the Antarctic Desert.",
   "What is the capital of Canada?":"The capital of Canada is Ottawa.",
   "data privacy":"Data privacy refers to the protection of personal and sensitive information from unauthorized access and use.",
   "What is the boiling point of alcohol?":"The boiling point of alcohol varies depending on the type of alcohol, but ethanols boiling point is approximately 78.37 degrees Celsius (173.07 degrees Fahrenheit).",
   "What is the chemical symbol for nitrogen?":"The chemical symbol for nitrogen is N.",
   "What is the population of India?":"As per our sources, the population of India is over 1.3 billion people.",
   "What is the meaning of the word innovation?":"The word innovation refers to the introduction of new ideas, methods, or products that bring about significant change or improvement.",
   "cloud computing":"Cloud computing is a technology that allows users to access and use computing resources, such as storage and processing power, over the internet.",
   "What is the chemical symbol for silver?":"The chemical symbol for silver is Ag.",
   "What is the largest continent in the world?":"The largest continent in the world is Asia.",
   "What is the capital of Italy?":"The capital of Italy is Rome.",
   "cybersecurity threats":"Cybersecurity threats include malware, phishing, hacking, and denial-of-service attacks aimed at compromising or damaging computer systems and data.",
   "What is the boiling point of carbon dioxide?":"The boiling point of carbon dioxide is approximately -78.5 degrees Celsius (-109.3 degrees Fahrenheit).",
   "What is the chemical symbol for sodium?":"The chemical symbol for sodium is Na.",
   "What is the population of Japan?":"As per our sources, the population of Japan is over 125 million people.",
   "What is the meaning of the word encryption?":"Encryption is the process of converting data or information into a code to prevent unauthorized access and maintain data security.",
   "5G technology":"5G technology is the fifth generation of wireless communication technology, providing faster data transfer rates and lower latency compared to previous generations.",
   "What is the currency of France?":"The currency of France is the Euro (€).",
   "What is the boiling point of oxygen?":"The boiling point of oxygen is approximately -183 degrees Celsius (-297.2 degrees Fahrenheit).",
   "What is the chemical symbol for potassium?":"The chemical symbol for potassium is K.",
   "What is the population of Russia?":"As per our sources, the population of Russia is over 145 million people."
} 
